In [25]:
import pandas as pd

In [33]:
df = pd.read_csv('/home/fer/Documents/cfDNA/OncoprintMerge/Base.v2.csv', header = None)
df

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,NaN,NaN,NaN,NaN,SubMolec,NaN,NaN,NaN,Luminal B Like HER2+,NaN,...,NaN,NaN,NaN,Luminal B Like HER2+,NaN,Luminal B Like HER2+,Luminal B,Triple Negativo,Luminal B Like HER2+,NaN
1,NaN,NaN,NaN,NaN,TumorFraction,0,0.01832,0.01756,0.01458,0.02001,...,NaN,0.01414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,M,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,NaN,NaN,NaN,NaN,N,0,0,0,0,1,...,0,1,1,3,2,2,2,2,0,1
4,NaN,NaN,NaN,NaN,T,1,1,2,2,4,...,4,2,2,0,4,4,4,2,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,SNV,Chromatin,VUS,NaN,NSD1,NaN,NaN,NaN,NaN,NaN,...,nonsynonymous SNV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,SNV,NaN,VUS,NaN,PDGFRA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,SNV,Transcription factor,VUS,NaN,RUNX1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,SNV,NaN,VUS,NaN,SETBP1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,nonsynonymous SNV,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,SNV,NaN,VUS,NaN,SIN3A,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
df = df.drop(list(range(0,11, 1)),axis=0)
df

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
11,Type,Function,Status,Cytoband,ID,UEB_0205,UEB_0208,UEB_0209,UEB_0210,UEB_0211,...,UEB_0227,UEB_0228,UEB_0229,UEB_0230,UEB_0231,UEB_0232,UEB_0233,UEB_0234,UEB_0235,UEB_0236
12,CNV,PI3K/mTOR,Uncertain significance,14q32.33,AKT1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,CNV,PI3K/mTOR,Uncertain significance,1q44-q43,AKT3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,CNV,Transcription factor,Likely pathogenic,Xq12,AR,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,loss,NaN,loss,NaN,NaN,NaN,NaN
15,CNV,Transcription factor,Uncertain significance,19q13.32,ARHGAP35,NaN,NaN,NaN,;loss_cfDNA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,SNV,Chromatin,VUS,NaN,NSD1,NaN,NaN,NaN,NaN,NaN,...,nonsynonymous SNV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,SNV,NaN,VUS,NaN,PDGFRA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,SNV,Transcription factor,VUS,NaN,RUNX1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,SNV,NaN,VUS,NaN,SETBP1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,nonsynonymous SNV,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,SNV,NaN,VUS,NaN,SIN3A,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
df.columns = list(df.loc[11])
df = df.drop(11,axis=0)
df

,Type,Function,Status,Cytoband,ID,UEB_0205,UEB_0208,UEB_0209,UEB_0210,UEB_0211,...,UEB_0227,UEB_0228,UEB_0229,UEB_0230,UEB_0231,UEB_0232,UEB_0233,UEB_0234,UEB_0235,UEB_0236
12,CNV,PI3K/mTOR,Uncertain significance,14q32.33,AKT1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,CNV,PI3K/mTOR,Uncertain significance,1q44-q43,AKT3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,CNV,Transcription factor,Likely pathogenic,Xq12,AR,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,loss,NaN,loss,NaN,NaN,NaN,NaN
15,CNV,Transcription factor,Uncertain significance,19q13.32,ARHGAP35,NaN,NaN,NaN,;loss_cfDNA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,CNV,Chromatin,Likely pathogenic,1p36.11,ARID1A,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,SNV,Chromatin,VUS,NaN,NSD1,NaN,NaN,NaN,NaN,NaN,...,nonsynonymous SNV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,SNV,NaN,VUS,NaN,PDGFRA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,SNV,Transcription factor,VUS,NaN,RUNX1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,SNV,NaN,VUS,NaN,SETBP1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,nonsynonymous SNV,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,SNV,NaN,VUS,NaN,SIN3A,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
df = df.drop(['Type', 'Function', 'Cytoband', 'Status'], axis=1)
df

,ID,UEB_0205,UEB_0208,UEB_0209,UEB_0210,UEB_0211,UEB_0212,UEB_0213,UEB_0214,UEB_0215,...,UEB_0227,UEB_0228,UEB_0229,UEB_0230,UEB_0231,UEB_0232,UEB_0233,UEB_0234,UEB_0235,UEB_0236
12,AKT1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,AKT3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;loss_cfDNA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,AR,NaN,NaN,NaN,NaN,NaN,loss,NaN,loss_tumor;,NaN,...,NaN,NaN,NaN,loss,NaN,loss,NaN,NaN,NaN,NaN
15,ARHGAP35,NaN,NaN,NaN,;loss_cfDNA,NaN,NaN,NaN,NaN,;loss_cfDNA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,ARID1A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;loss_cfDNA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,NSD1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,nonsynonymous SNV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,PDGFRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,RUNX1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,SETBP1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,nonsynonymous SNV,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,SIN3A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
# Tumor
columnas = df.columns
genes = list(df['ID'])

i = 1
df_bd = pd.DataFrame()

while i < len(columnas):
    lst_i = []
    for j in df[columnas[i]]:
        if j == 'loss_tumor;loss_cfDNA' or j == 'gain_tumor;' or j == 'loss_tumor;' or j == 'loss' or j =='gain' or j == 'nonsynonymous SNV' or j == 'HotSpot':
            lst_i.append(1)
        else:
            lst_i.append(0)
    df_bd[i] = lst_i
    i=i+1

df_bd.insert(0, "ID", genes)
df_bd.columns = columnas
df_tumor = df_bd
df_tumor

,ID,UEB_0205,UEB_0208,UEB_0209,UEB_0210,UEB_0211,UEB_0212,UEB_0213,UEB_0214,UEB_0215,...,UEB_0227,UEB_0228,UEB_0229,UEB_0230,UEB_0231,UEB_0232,UEB_0233,UEB_0234,UEB_0235,UEB_0236
0,AKT1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,AKT3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,AR,0,0,0,0,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,0
3,ARHGAP35,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ARID1A,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,NSD1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
109,PDGFRA,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
110,RUNX1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
111,SETBP1,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
112,SIN3A,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [38]:
# cfDNA
i = 1
df_bd = pd.DataFrame()

while i < len(columnas):
    lst_i = []
    for j in df[columnas[i]]:
        if j == 'loss_tumor;loss_cfDNA' or j == ';loss_cfDNA' or j == ';gain_cfDNA':
            lst_i.append(1)
        else:
            lst_i.append(0)
    df_bd[i] = lst_i
    i=i+1

df_bd.insert(0, "ID", genes)
df_bd.columns = columnas
df_cfDNA = df_bd
df_cfDNA

,ID,UEB_0205,UEB_0208,UEB_0209,UEB_0210,UEB_0211,UEB_0212,UEB_0213,UEB_0214,UEB_0215,...,UEB_0227,UEB_0228,UEB_0229,UEB_0230,UEB_0231,UEB_0232,UEB_0233,UEB_0234,UEB_0235,UEB_0236
0,AKT1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,AKT3,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,AR,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,ARHGAP35,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,ARID1A,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,NSD1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
109,PDGFRA,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
110,RUNX1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
111,SETBP1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
112,SIN3A,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [39]:
df_tumor.to_csv('/home/fer/Documents/cfDNA/OncoprintMerge/TumorFilterv2.csv')
df_cfDNA.to_csv('/home/fer/Documents/cfDNA/OncoprintMerge/cfDNAFilterv2.csv')