In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/home/fer/Documents/cfDNA/Tumor/Colombia_Merge.wNULL.txt', sep = '\t')
df

/tmp/ipykernel_23182/1884020921.py:1: DtypeWarning: Columns (33,34,35,36,37,38,42,46,49,52,55,58,61,64,67,72,75,78,86,87,107,108,109) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/home/fer/Documents/cfDNA/Tumor/Colombia_Merge.wNULL.txt', sep = '\t')

,Sample,Chr,Start,End,Ref,Alt,Func.refGene,Gene.refGene,GeneDetail.refGene,ExonicFunc.refGene,...,Otherinfo.3,Otherinfo.4,Otherinfo.5,Otherinfo.6,Otherinfo.7,Otherinfo.8,Otherinfo.9,Otherinfo.10,Otherinfo.11,Otherinfo.12
0,UEB_10,chr1,527018,527018,G,A,intergenic,OR4F16;LOC101928626,dist=158421;dist=35742,NaN,...,chr1,527018,NaN,G,A,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=1,1|1,1;DP=4;...",GT:AD:AF:DP:F1R2:F2R1:PGT:PID:PS:SB,"0|1:2,2:0.500:4:2,2:0,0:0|1:527018_G_A:527018:..."
1,UEB_10,chr1,527030,527030,C,T,intergenic,OR4F16;LOC101928626,dist=158433;dist=35730,NaN,...,chr1,527030,NaN,C,T,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=1,1|1,1;DP=4;...",GT:AD:AF:DP:F1R2:F2R1:PGT:PID:PS:SB,"0|1:2,2:0.500:4:2,2:0,0:0|1:527018_G_A:527018:..."
2,UEB_10,chr1,863641,863641,G,A,intronic,SAMD11,NaN,NaN,...,chr1,863641,NaN,G,A,NaN,clustered_events;haplotype,"AS_FilterStatus=SITE;AS_SB_TABLE=0,0|0,0;DP=2;...",GT:AD:AF:DP:F1R2:F2R1:PGT:PID:PS:SB,"0|1:0,2:0.750:2:0,1:0,0:0|1:863641_G_A:863641:..."
3,UEB_10,chr1,863644,863644,T,C,intronic,SAMD11,NaN,NaN,...,chr1,863644,NaN,T,C,NaN,clustered_events;haplotype,"AS_FilterStatus=SITE;AS_SB_TABLE=0,0|0,0;DP=2;...",GT:AD:AF:DP:F1R2:F2R1:PGT:PID:PS:SB,"0|1:0,2:0.750:2:0,2:0,0:0|1:863641_G_A:863641:..."
4,UEB_10,chr1,863689,863689,A,G,intronic,SAMD11,NaN,NaN,...,chr1,863689,NaN,A,G,NaN,clustered_events,"AS_FilterStatus=SITE;AS_SB_TABLE=0,0|0,0;DP=2;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:0,2:0.750:2:0,2:0,0:0,0,2,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2136064,UEB_86,chrUn_gl000226,14292,14292,G,C,intergenic,NONE;NONE,dist=NONE;dist=NONE,NaN,...,chrUn_gl000226,14292,NaN,G,C,NaN,map_qual,"AS_FilterStatus=map_qual;AS_SB_TABLE=2,0|1,1;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:2,2:0.400:4:1,2:1,0:2,0,1,1"
2136065,UEB_86,chrUn_gl000226,14300,14300,T,G,intergenic,NONE;NONE,dist=NONE;dist=NONE,NaN,...,chrUn_gl000226,14300,NaN,T,G,NaN,map_qual;weak_evidence,"AS_FilterStatus=weak_evidence,map_qual;AS_SB_T...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:4,1:0.333:5:4,0:0,1:3,1,1,0"
2136066,UEB_86,chrUn_gl000226,14383,14383,A,T,intergenic,NONE;NONE,dist=NONE;dist=NONE,NaN,...,chrUn_gl000226,14383,NaN,A,T,NaN,clustered_events;map_qual,"AS_FilterStatus=map_qual;AS_SB_TABLE=0,0|3,4;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:0,7:0.863:7:0,2:0,5:0,0,3,4"
2136067,UEB_86,chrUn_gl000226,14428,14428,A,C,intergenic,NONE;NONE,dist=NONE;dist=NONE,NaN,...,chrUn_gl000226,14428,NaN,A,C,NaN,clustered_events;map_qual,"AS_FilterStatus=map_qual;AS_SB_TABLE=2,3|1,1;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:5,2:0.286:7:2,0:3,2:2,3,1,1"
2136068,UEB_86,chrUn_gl000226,14431,14431,C,T,intergenic,NONE;NONE,dist=NONE;dist=NONE,NaN,...,chrUn_gl000226,14431,NaN,C,T,NaN,clustered_events;map_qual,"AS_FilterStatus=map_qual;AS_SB_TABLE=0,0|3,4;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:0,7:0.857:7:0,2:0,5:0,0,3,4"

In [4]:
df['ExonicFunc.refGene'].value_counts()

synonymous SNV                8367
nonsynonymous SNV             8046
nonframeshift deletion        2264
nonframeshift insertion        677
frameshift deletion            586
stopgain                       416
frameshift insertion           325
unknown                        252
nonframeshift substitution     214
stoploss                        10
startloss                        6
Name: ExonicFunc.refGene, dtype: int64

In [11]:
df['Func.refGene'].value_counts()

intergenic               1091189
intronic                  825814
ncRNA_intronic            121299
UTR3                       26161
exonic                     21152
downstream                 17105
upstream                   16708
ncRNA_exonic                9046
UTR5                        6188
upstream;downstream         1026
splicing                     299
ncRNA_exonic;splicing         34
ncRNA_splicing                30
exonic;splicing               11
UTR5;UTR3                      7
Name: Func.refGene, dtype: int64

In [16]:
df_UTR = df[(df['Gene.refGene']=='SMAD4') & ((df['Func.refGene']=='UTR3') | (df['Func.refGene']=='UTR5') | (df['Func.refGene']=='UTR5;UTR3'))]
df_UTR

,Sample,Chr,Start,End,Ref,Alt,Func.refGene,Gene.refGene,GeneDetail.refGene,ExonicFunc.refGene,...,Otherinfo.3,Otherinfo.4,Otherinfo.5,Otherinfo.6,Otherinfo.7,Otherinfo.8,Otherinfo.9,Otherinfo.10,Otherinfo.11,Otherinfo.12
36261,UEB_10,chr18,48606336,48606336,T,-,UTR3,SMAD4,NM_005359:c.*1499delT,NaN,...,chr18,48606335,NaN,GT,G,NaN,multiallelic;slippage,AS_FilterStatus=SITE|weak_evidence;AS_SB_TABLE...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:91,18,11:0.131,0.098:120:55,9,6:32,9,5:5..."
36262,UEB_10,chr18,48609103,48609103,T,-,UTR3,SMAD4,NM_005359:c.*4266delT,NaN,...,chr18,48609102,NaN,GT,G,NaN,multiallelic;slippage,"AS_FilterStatus=SITE|SITE;AS_SB_TABLE=70,69|12...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:139,23,50:0.092,0.207:212:71,13,20:67,10..."
36263,UEB_10,chr18,48609832,48609832,T,-,UTR3,SMAD4,NM_005359:c.*4995delT,NaN,...,chr18,48609831,NaN,GT,G,NaN,multiallelic;slippage,AS_FilterStatus=weak_evidence|SITE;AS_SB_TABLE...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:187,9,46:0.036,0.177:242:92,5,21:89,4,23..."
36264,UEB_10,chr18,48609968,48609968,A,G,UTR3,SMAD4,NM_005359:c.*5131A>G,NaN,...,chr18,48609968,NaN,A,G,NaN,panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=100,57|111,66...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:157,177:0.521:334:81,80:74,92:100,57,111,66"
36265,UEB_10,chr18,48610371,48610372,CA,-,UTR3,SMAD4,NM_005359:c.*5534_*5535delCA,NaN,...,chr18,48610370,NaN,GCA,G,NaN,clustered_events;panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=74,67|73,67;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:141,140:0.510:281:49,72:84,65:74,67,73,67"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2077183,UEB_8,chr18,48610698,48610702,AAGAA,-,UTR3,SMAD4,NM_005359:c.*5861_*5865delAAGAA,NaN,...,chr18,48610697,NaN,CAAGAA,C,NaN,panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=0,0|113,127;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:0,240:0.994:240:0,116:0,121:0,0,113,127"
2077184,UEB_8,chr18,48610831,48610831,A,C,UTR3,SMAD4,NM_005359:c.*5994A>C,NaN,...,chr18,48610831,NaN,A,C,NaN,panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=1,0|223,58;DP...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:1,281:0.992:282:0,137:1,139:1,0,223,58"
2129545,UEB_86,chr18,48609103,48609103,T,-,UTR3,SMAD4,NM_005359:c.*4266delT,NaN,...,chr18,48609102,NaN,GT,G,NaN,multiallelic;slippage,AS_FilterStatus=weak_evidence|SITE;AS_SB_TABLE...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:71,8,13:0.097,0.165:92:36,3,8:35,5,5:38,..."
2129546,UEB_86,chr18,48609832,48609832,T,-,UTR3,SMAD4,NM_005359:c.*4995delT,NaN,...,chr18,48609831,NaN,GT,G,NaN,multiallelic;slippage,AS_FilterStatus=weak_evidence|SITE;AS_SB_TABLE...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:89,8,14:0.074,0.130:111:42,7,8:47,1,6:38..."
2129547,UEB_86,chr18,48610382,48610382,G,A,UTR3,SMAD4,NM_005359:c.*5545G>A,NaN,...,chr18,48610382,NaN,GCACACA,ACACACA,NaN,multiallelic,AS_FilterStatus=weak_evidence|weak_evidence|SI...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2/3/4/5/6:8,4,10,24,120,7,23:0.029,0.057,0..."

In [73]:
#df_UTR.to_csv('/home/fer/Review.csv')

In [17]:
df_UTR['Func.refGene'].value_counts()

UTR3    357
UTR5      5
Name: Func.refGene, dtype: int64

In [35]:
x = df_UTR[df_UTR['Sample']=='UEB_47']
print(x['ClinVar_SIG'].to_list())
x

[nan, nan, nan, nan, nan, nan, 'Uncertain significance|Uncertain significance|Uncertain significance', 'Uncertain significance|Uncertain significance|Uncertain significance']

,Sample,Chr,Start,End,Ref,Alt,Func.refGene,Gene.refGene,GeneDetail.refGene,ExonicFunc.refGene,...,Otherinfo.3,Otherinfo.4,Otherinfo.5,Otherinfo.6,Otherinfo.7,Otherinfo.8,Otherinfo.9,Otherinfo.10,Otherinfo.11,Otherinfo.12
1308994,UEB_47,chr18,48605008,48605008,T,-,UTR3,SMAD4,NM_005359:c.*171delT,NaN,...,chr18,48605007,NaN,AT,A,NaN,slippage,"AS_FilterStatus=SITE;AS_SB_TABLE=114,129|11,8;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:243,19:0.070:262:122,6:121,13:114,129,11,8"
1308995,UEB_47,chr18,48606178,48606178,-,T,UTR3,SMAD4,NM_005359:c.*1341_*1342insT,NaN,...,chr18,48606178,NaN,A,AT,NaN,slippage;weak_evidence,"AS_FilterStatus=weak_evidence;AS_SB_TABLE=77,9...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:167,12:0.058:179:79,6:85,6:77,90,6,6"
1308996,UEB_47,chr18,48606336,48606337,TT,-,UTR3,SMAD4,NM_005359:c.*1499_*1500delTT,NaN,...,chr18,48606335,NaN,GTT,G,NaN,multiallelic,AS_FilterStatus=weak_evidence|SITE;AS_SB_TABLE...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:68,5,26:0.053,0.238:99:42,1,18:26,4,8:35..."
1308997,UEB_47,chr18,48609103,48609103,T,-,UTR3,SMAD4,NM_005359:c.*4266delT,NaN,...,chr18,48609102,NaN,GT,G,NaN,multiallelic;slippage,AS_FilterStatus=weak_evidence|SITE;AS_SB_TABLE...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:141,13,32:0.060,0.150:186:75,8,19:65,5,1..."
1308998,UEB_47,chr18,48609831,48609831,-,T,UTR3,SMAD4,NM_005359:c.*4994_*4995insT,NaN,...,chr18,48609831,NaN,G,GT,NaN,slippage,"AS_FilterStatus=SITE;AS_SB_TABLE=90,139|11,17;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:229,28:0.093:257:114,9:109,19:90,139,11,17"
1308999,UEB_47,chr18,48610380,48610380,-,CACACA,UTR3,SMAD4,NM_005359:c.*5543_*5544insCACACA,NaN,...,chr18,48610380,NaN,G,GCACACA,NaN,clustered_events;multiallelic;weak_evidence,AS_FilterStatus=weak_evidence|weak_evidence;AS...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:158,3,5:0.042,0.038:166:69,0,1:86,3,4:82..."
1309000,UEB_47,chr18,48610382,48610382,G,A,UTR3,SMAD4,NM_005359:c.*5545G>A,NaN,...,chr18,48610382,NaN,G,A,NaN,clustered_events;multiallelic,AS_FilterStatus=SITE|SITE|weak_evidence|weak_e...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2/3/4/5:3,19,38,8,6,37:0.150,0.323,0.072,0..."
1309001,UEB_47,chr18,48610584,48610584,-,T,UTR3,SMAD4,NM_005359:c.*5747_*5748insT,NaN,...,chr18,48610584,NaN,A,AT,NaN,clustered_events;panel_of_normals;slippage;wea...,"AS_FilterStatus=weak_evidence;AS_SB_TABLE=145,...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:268,20:0.061:288:143,12:122,8:145,123,12,8"

In [53]:
z = '0/1:243,19:0.070:262:122,6:121,13:114,129,11,8'
z.replace(',', )

'0/1:243,19:0.070:262:122,6:121,13:114,129,11,8'

In [62]:
z = df['Otherinfo.11'][1].split(':')
z = z[0:7]
z

['GT', 'AD', 'AF', 'DP', 'F1R2', 'F2R1', 'PGT']

In [63]:
x[z] = x['Otherinfo.12'].str.split(":", expand = True)

/tmp/ipykernel_23182/572369791.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[z] = x['Otherinfo.12'].str.split(":", expand = True)
/tmp/ipykernel_23182/572369791.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[z] = x['Otherinfo.12'].str.split(":", expand = True)
/tmp/ipykernel_23182/572369791.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[z] = x['Otherinfo.12'].str.split(":", expand = True)
/tmp/ipykernel_23182/572369791.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[z] = x['Otherinfo.12'].str.split(":", expand = True)
/tmp/ipykernel_23182/572369791.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[z] = x['Otherinfo.12'].str.split(":", expand = True)
/tmp/ipykernel_23182/572369791.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[z] = x['Otherinfo.12'].str.split(":", expand = True)
/tmp/ipykernel_23182/572369791.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[z] = x['Otherinfo.12'].str.split(":", expand = True)

In [64]:
x

,Sample,Chr,Start,End,Ref,Alt,Func.refGene,Gene.refGene,GeneDetail.refGene,ExonicFunc.refGene,...,Otherinfo.10,Otherinfo.11,Otherinfo.12,GT,AD,AF,DP,F1R2,F2R1,PGT
1308994,UEB_47,chr18,48605008,48605008,T,-,UTR3,SMAD4,NM_005359:c.*171delT,NaN,...,"AS_FilterStatus=SITE;AS_SB_TABLE=114,129|11,8;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:243,19:0.070:262:122,6:121,13:114,129,11,8",0/1,"243,19",0.070,262,"122,6","121,13","114,129,11,8"
1308995,UEB_47,chr18,48606178,48606178,-,T,UTR3,SMAD4,NM_005359:c.*1341_*1342insT,NaN,...,"AS_FilterStatus=weak_evidence;AS_SB_TABLE=77,9...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:167,12:0.058:179:79,6:85,6:77,90,6,6",0/1,"167,12",0.058,179,"79,6","85,6","77,90,6,6"
1308996,UEB_47,chr18,48606336,48606337,TT,-,UTR3,SMAD4,NM_005359:c.*1499_*1500delTT,NaN,...,AS_FilterStatus=weak_evidence|SITE;AS_SB_TABLE...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:68,5,26:0.053,0.238:99:42,1,18:26,4,8:35...",0/1/2,"68,5,26","0.053,0.238",99,"42,1,18","26,4,8","35,33,18,13"
1308997,UEB_47,chr18,48609103,48609103,T,-,UTR3,SMAD4,NM_005359:c.*4266delT,NaN,...,AS_FilterStatus=weak_evidence|SITE;AS_SB_TABLE...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:141,13,32:0.060,0.150:186:75,8,19:65,5,1...",0/1/2,"141,13,32","0.060,0.150",186,"75,8,19","65,5,12","75,66,23,22"
1308998,UEB_47,chr18,48609831,48609831,-,T,UTR3,SMAD4,NM_005359:c.*4994_*4995insT,NaN,...,"AS_FilterStatus=SITE;AS_SB_TABLE=90,139|11,17;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:229,28:0.093:257:114,9:109,19:90,139,11,17",0/1,"229,28",0.093,257,"114,9","109,19","90,139,11,17"
1308999,UEB_47,chr18,48610380,48610380,-,CACACA,UTR3,SMAD4,NM_005359:c.*5543_*5544insCACACA,NaN,...,AS_FilterStatus=weak_evidence|weak_evidence;AS...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:158,3,5:0.042,0.038:166:69,0,1:86,3,4:82...",0/1/2,"158,3,5","0.042,0.038",166,"69,0,1","86,3,4","82,76,4,4"
1309000,UEB_47,chr18,48610382,48610382,G,A,UTR3,SMAD4,NM_005359:c.*5545G>A,NaN,...,AS_FilterStatus=SITE|SITE|weak_evidence|weak_e...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2/3/4/5:3,19,38,8,6,37:0.150,0.323,0.072,0...",0/1/2/3/4/5,"3,19,38,8,6,37","0.150,0.323,0.072,0.048,0.374",111,"1,5,22,5,3,14","1,14,14,2,2,23","1,2,59,49"
1309001,UEB_47,chr18,48610584,48610584,-,T,UTR3,SMAD4,NM_005359:c.*5747_*5748insT,NaN,...,"AS_FilterStatus=weak_evidence;AS_SB_TABLE=145,...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:268,20:0.061:288:143,12:122,8:145,123,12,8",0/1,"268,20",0.061,288,"143,12","122,8","145,123,12,8"

In [69]:
x = df_UTR[df_UTR['Sample']=='UEB_47']
print(x['ClinVar_SIG'].to_list())
x

[nan, nan, nan, nan, nan, nan, 'Uncertain significance|Uncertain significance|Uncertain significance', 'Uncertain significance|Uncertain significance|Uncertain significance']

,Sample,Chr,Start,End,Ref,Alt,Func.refGene,Gene.refGene,GeneDetail.refGene,ExonicFunc.refGene,...,Otherinfo.3,Otherinfo.4,Otherinfo.5,Otherinfo.6,Otherinfo.7,Otherinfo.8,Otherinfo.9,Otherinfo.10,Otherinfo.11,Otherinfo.12
1308994,UEB_47,chr18,48605008,48605008,T,-,UTR3,SMAD4,NM_005359:c.*171delT,NaN,...,chr18,48605007,NaN,AT,A,NaN,slippage,"AS_FilterStatus=SITE;AS_SB_TABLE=114,129|11,8;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:243,19:0.070:262:122,6:121,13:114,129,11,8"
1308995,UEB_47,chr18,48606178,48606178,-,T,UTR3,SMAD4,NM_005359:c.*1341_*1342insT,NaN,...,chr18,48606178,NaN,A,AT,NaN,slippage;weak_evidence,"AS_FilterStatus=weak_evidence;AS_SB_TABLE=77,9...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:167,12:0.058:179:79,6:85,6:77,90,6,6"
1308996,UEB_47,chr18,48606336,48606337,TT,-,UTR3,SMAD4,NM_005359:c.*1499_*1500delTT,NaN,...,chr18,48606335,NaN,GTT,G,NaN,multiallelic,AS_FilterStatus=weak_evidence|SITE;AS_SB_TABLE...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:68,5,26:0.053,0.238:99:42,1,18:26,4,8:35..."
1308997,UEB_47,chr18,48609103,48609103,T,-,UTR3,SMAD4,NM_005359:c.*4266delT,NaN,...,chr18,48609102,NaN,GT,G,NaN,multiallelic;slippage,AS_FilterStatus=weak_evidence|SITE;AS_SB_TABLE...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:141,13,32:0.060,0.150:186:75,8,19:65,5,1..."
1308998,UEB_47,chr18,48609831,48609831,-,T,UTR3,SMAD4,NM_005359:c.*4994_*4995insT,NaN,...,chr18,48609831,NaN,G,GT,NaN,slippage,"AS_FilterStatus=SITE;AS_SB_TABLE=90,139|11,17;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:229,28:0.093:257:114,9:109,19:90,139,11,17"
1308999,UEB_47,chr18,48610380,48610380,-,CACACA,UTR3,SMAD4,NM_005359:c.*5543_*5544insCACACA,NaN,...,chr18,48610380,NaN,G,GCACACA,NaN,clustered_events;multiallelic;weak_evidence,AS_FilterStatus=weak_evidence|weak_evidence;AS...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:158,3,5:0.042,0.038:166:69,0,1:86,3,4:82..."
1309000,UEB_47,chr18,48610382,48610382,G,A,UTR3,SMAD4,NM_005359:c.*5545G>A,NaN,...,chr18,48610382,NaN,G,A,NaN,clustered_events;multiallelic,AS_FilterStatus=SITE|SITE|weak_evidence|weak_e...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2/3/4/5:3,19,38,8,6,37:0.150,0.323,0.072,0..."
1309001,UEB_47,chr18,48610584,48610584,-,T,UTR3,SMAD4,NM_005359:c.*5747_*5748insT,NaN,...,chr18,48610584,NaN,A,AT,NaN,clustered_events;panel_of_normals;slippage;wea...,"AS_FilterStatus=weak_evidence;AS_SB_TABLE=145,...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:268,20:0.061:288:143,12:122,8:145,123,12,8"

In [70]:
x = df_UTR[df_UTR['Sample']=='UEB_44']
print(x['ClinVar_SIG'].to_list())
x

[nan, nan, 'Uncertain significance|Uncertain significance|Uncertain significance', nan, nan, nan, nan, 'Benign|Benign|Benign', 'Benign|Benign|Benign']

,Sample,Chr,Start,End,Ref,Alt,Func.refGene,Gene.refGene,GeneDetail.refGene,ExonicFunc.refGene,...,Otherinfo.3,Otherinfo.4,Otherinfo.5,Otherinfo.6,Otherinfo.7,Otherinfo.8,Otherinfo.9,Otherinfo.10,Otherinfo.11,Otherinfo.12
1212129,UEB_44,chr18,48606336,48606336,T,-,UTR3,SMAD4,NM_005359:c.*1499delT,NaN,...,chr18,48606335,NaN,GT,G,NaN,multiallelic;slippage,AS_FilterStatus=weak_evidence|SITE;AS_SB_TABLE...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:88,15,30:0.104,0.188:133:34,12,8:53,3,21..."
1212130,UEB_44,chr18,48609103,48609103,T,-,UTR3,SMAD4,NM_005359:c.*4266delT,NaN,...,chr18,48609102,NaN,GT,G,NaN,multiallelic;slippage,"AS_FilterStatus=SITE|SITE;AS_SB_TABLE=75,69|15...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:144,29,35:0.108,0.142:208:71,13,20:73,16..."
1212131,UEB_44,chr18,48609819,48609819,-,T,UTR3,SMAD4,NM_005359:c.*4982_*4983insT,NaN,...,chr18,48609819,NaN,C,CT,NaN,contamination;panel_of_normals;slippage;weak_e...,"AS_FilterStatus=weak_evidence,contamination;AS...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:233,11:0.046:244:101,5:128,6:97,136,3,8"
1212132,UEB_44,chr18,48609832,48609832,T,-,UTR3,SMAD4,NM_005359:c.*4995delT,NaN,...,chr18,48609831,NaN,GT,G,NaN,multiallelic;slippage,AS_FilterStatus=weak_evidence|SITE;AS_SB_TABLE...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:186,18,30:0.069,0.131:234:75,11,18:109,7..."
1212133,UEB_44,chr18,48610371,48610372,CA,-,UTR3,SMAD4,NM_005359:c.*5534_*5535delCA,NaN,...,chr18,48610370,NaN,GCA,G,NaN,clustered_events;panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=0,2|145,139;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:2,284:0.987:286:0,85:1,122:0,2,145,139"
1212134,UEB_44,chr18,48610375,48610386,CGCGCGCGCACA,-,UTR3,SMAD4,NM_005359:c.*5538_*5549delCGCGCGCGCACA,NaN,...,chr18,48610374,NaN,GCGCGCGCGCACA,G,NaN,clustered_events;contamination;panel_of_normal...,"AS_FilterStatus=weak_evidence,contamination;AS...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:277,8:0.033:285:79,5:120,2:140,137,5,3"
1212135,UEB_44,chr18,48610377,48610392,CGCGCGCACACACACA,-,UTR3,SMAD4,NM_005359:c.*5540_*5555delCGCGCGCACACACACA,NaN,...,chr18,48610376,NaN,GCGCGCGCACACACACA,G,NaN,clustered_events;multiallelic,"AS_FilterStatus=weak_evidence,contamination|SI...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2/3/4:3,4,27,164,15:0.029,0.140,0.756,0.06..."
1212136,UEB_44,chr18,48610698,48610702,AAGAA,-,UTR3,SMAD4,NM_005359:c.*5861_*5865delAAGAA,NaN,...,chr18,48610697,NaN,CAAGAA,C,NaN,panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=0,0|173,131;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:0,304:0.996:304:0,172:0,130:0,0,173,131"
1212137,UEB_44,chr18,48610831,48610831,A,C,UTR3,SMAD4,NM_005359:c.*5994A>C,NaN,...,chr18,48610831,NaN,A,C,NaN,panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=0,0|246,66;DP...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:0,312:0.997:312:0,166:0,140:0,0,246,66"

In [71]:
df_UTR = df[(df['Gene.refGene']=='STK11') & ((df['Func.refGene']=='UTR3') | (df['Func.refGene']=='UTR5') | (df['Func.refGene']=='UTR5;UTR3'))]
df_UTR

,Sample,Chr,Start,End,Ref,Alt,Func.refGene,Gene.refGene,GeneDetail.refGene,ExonicFunc.refGene,...,Otherinfo.3,Otherinfo.4,Otherinfo.5,Otherinfo.6,Otherinfo.7,Otherinfo.8,Otherinfo.9,Otherinfo.10,Otherinfo.11,Otherinfo.12
37587,UEB_10,chr19,1206796,1206796,-,T,UTR5,STK11,NM_000455:c.-117_-116insT,NaN,...,chr19,1206796,NaN,C,CT,NaN,panel_of_normals;slippage,"AS_FilterStatus=SITE;AS_SB_TABLE=112,81|10,15;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:193,25:0.103:218:88,15:96,10:112,81,10,15"
37605,UEB_10,chr19,1228059,1228059,T,-,UTR3,STK11,NM_000455:c.*484delT,NaN,...,chr19,1228058,NaN,CT,C,NaN,panel_of_normals;slippage,"AS_FilterStatus=SITE;AS_SB_TABLE=56,64|6,8;DP=...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:120,14:0.101:134:58,7:60,7:56,64,6,8"
37606,UEB_10,chr19,1228191,1228191,T,C,UTR3,STK11,NM_000455:c.*616T>C,NaN,...,chr19,1228191,NaN,T,C,NaN,panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=0,1|147,152;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:1,299:0.990:300:1,140:0,156:0,1,147,152"
37607,UEB_10,chr19,1228413,1228421,AAGCTTGGG,-,UTR3,STK11,NM_000455:c.*838_*846delAAGCTTGGG,NaN,...,chr19,1228412,NaN,AAAGCTTGGG,A,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=0,0|91,99;DP=...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:0,190:0.993:190:0,100:0,89:0,0,91,99"
120851,UEB_14,chr19,1228058,1228058,-,T,UTR3,STK11,NM_000455:c.*483_*484insT,NaN,...,chr19,1228058,NaN,C,CT,NaN,panel_of_normals;slippage;weak_evidence,"AS_FilterStatus=weak_evidence;AS_SB_TABLE=44,5...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:100,9:0.089:109:50,6:46,3:44,56,1,8"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2032190,UEB_84,chr19,1228191,1228191,T,C,UTR3,STK11,NM_000455:c.*616T>C,NaN,...,chr19,1228191,NaN,T,C,NaN,panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=86,48|78,48;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:134,126:0.469:260:69,66:65,60:86,48,78,48"
2078671,UEB_8,chr19,1228059,1228059,T,-,UTR3,STK11,NM_000455:c.*484delT,NaN,...,chr19,1228058,NaN,CT,C,NaN,multiallelic;panel_of_normals;slippage,AS_FilterStatus=weak_evidence|SITE;AS_SB_TABLE...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:92,12,25:0.073,0.171:129:46,7,12:43,4,13..."
2078672,UEB_8,chr19,1228191,1228191,T,C,UTR3,STK11,NM_000455:c.*616T>C,NaN,...,chr19,1228191,NaN,T,C,NaN,panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=75,71|72,75;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:146,147:0.507:293:70,83:74,63:75,71,72,75"
2131714,UEB_86,chr19,1228059,1228059,T,-,UTR3,STK11,NM_000455:c.*484delT,NaN,...,chr19,1228058,NaN,CT,C,NaN,panel_of_normals;slippage;weak_evidence,"AS_FilterStatus=weak_evidence;AS_SB_TABLE=35,3...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:68,11:0.125:79:36,8:32,3:35,33,6,5"
2131715,UEB_86,chr19,1228191,1228191,T,C,UTR3,STK11,NM_000455:c.*616T>C,NaN,...,chr19,1228191,NaN,T,C,NaN,panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=0,0|84,85;DP=...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:0,169:0.991:169:0,82:0,85:0,0,84,85"

In [72]:
df_UTR[df_UTR['Sample'] == 'UEB_14']
#VUS Y BENIGNA

,Sample,Chr,Start,End,Ref,Alt,Func.refGene,Gene.refGene,GeneDetail.refGene,ExonicFunc.refGene,...,Otherinfo.3,Otherinfo.4,Otherinfo.5,Otherinfo.6,Otherinfo.7,Otherinfo.8,Otherinfo.9,Otherinfo.10,Otherinfo.11,Otherinfo.12
120851,UEB_14,chr19,1228058,1228058,-,T,UTR3,STK11,NM_000455:c.*483_*484insT,NaN,...,chr19,1228058,NaN,C,CT,NaN,panel_of_normals;slippage;weak_evidence,"AS_FilterStatus=weak_evidence;AS_SB_TABLE=44,5...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:100,9:0.089:109:50,6:46,3:44,56,1,8"
120852,UEB_14,chr19,1228191,1228191,T,C,UTR3,STK11,NM_000455:c.*616T>C,NaN,...,chr19,1228191,NaN,T,C,NaN,panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=0,0|123,110;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:0,233:0.994:233:0,117:0,112:0,0,123,110"

In [74]:
df_UTR[df_UTR['Sample'] == 'UEB_44']
# Conflicting, benigna y VUS

,Sample,Chr,Start,End,Ref,Alt,Func.refGene,Gene.refGene,GeneDetail.refGene,ExonicFunc.refGene,...,Otherinfo.3,Otherinfo.4,Otherinfo.5,Otherinfo.6,Otherinfo.7,Otherinfo.8,Otherinfo.9,Otherinfo.10,Otherinfo.11,Otherinfo.12
1213730,UEB_44,chr19,1206796,1206796,-,T,UTR5,STK11,NM_000455:c.-117_-116insT,NaN,...,chr19,1206796,NaN,C,CT,NaN,contamination;panel_of_normals;slippage;weak_e...,"AS_FilterStatus=weak_evidence,contamination;AS...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:239,11:0.044:250:138,7:101,4:132,107,3,8"
1213749,UEB_44,chr19,1228191,1228191,T,C,UTR3,STK11,NM_000455:c.*616T>C,NaN,...,chr19,1228191,NaN,T,C,NaN,panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=26,72|35,81;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:98,116:0.525:214:58,48:40,68:26,72,35,81"
1213750,UEB_44,chr19,1228243,1228243,C,A,UTR3,STK11,NM_000455:c.*668C>A,NaN,...,chr19,1228243,NaN,C,A,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=27,46|35,57;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:73,92:0.576:165:39,38:33,53:27,46,35,57"

In [75]:
df_UTR[df_UTR['Sample'] == 'UEB_49']
# VUS, error, VUS, Benigna

,Sample,Chr,Start,End,Ref,Alt,Func.refGene,Gene.refGene,GeneDetail.refGene,ExonicFunc.refGene,...,Otherinfo.3,Otherinfo.4,Otherinfo.5,Otherinfo.6,Otherinfo.7,Otherinfo.8,Otherinfo.9,Otherinfo.10,Otherinfo.11,Otherinfo.12
1361620,UEB_49,chr19,1206106,1206106,G,A,UTR5,STK11,NM_000455:c.-807G>A,NaN,...,chr19,1206106,NaN,G,A,NaN,contamination;weak_evidence,"AS_FilterStatus=weak_evidence,contamination;AS...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:232,4:0.019:236:118,2:113,2:107,125,2,2"
1361621,UEB_49,chr19,1206797,1206797,T,-,UTR5,STK11,NM_000455:c.-116del-,NaN,...,chr19,1206796,NaN,CT,C,NaN,multiallelic;panel_of_normals;slippage;weak_ev...,AS_FilterStatus=weak_evidence|weak_evidence;AS...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:286,12,20:0.034,0.053:318:147,7,9:135,5,..."
1361641,UEB_49,chr19,1228059,1228059,T,-,UTR3,STK11,NM_000455:c.*484delT,NaN,...,chr19,1228058,NaN,CT,C,NaN,multiallelic;panel_of_normals;slippage,"AS_FilterStatus=SITE|SITE;AS_SB_TABLE=84,99|10...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:183,21,25:0.083,0.100:229:79,14,16:101,7..."
1361642,UEB_49,chr19,1228191,1228191,T,C,UTR3,STK11,NM_000455:c.*616T>C,NaN,...,chr19,1228191,NaN,T,C,NaN,panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=90,130|100,12...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:220,225:0.502:445:93,99:127,124:90,130,100..."

# RUNX1

In [76]:
df_UTR = df[(df['Gene.refGene']=='RUNX1') & ((df['Func.refGene']=='UTR3') | (df['Func.refGene']=='UTR5') | (df['Func.refGene']=='UTR5;UTR3'))]
df_UTR

,Sample,Chr,Start,End,Ref,Alt,Func.refGene,Gene.refGene,GeneDetail.refGene,ExonicFunc.refGene,...,Otherinfo.3,Otherinfo.4,Otherinfo.5,Otherinfo.6,Otherinfo.7,Otherinfo.8,Otherinfo.9,Otherinfo.10,Otherinfo.11,Otherinfo.12
40498,UEB_10,chr21,36161902,36161903,CA,-,UTR3,RUNX1,NM_001754:c.*2530_*2529delTG;NM_001001890:c.*2...,NaN,...,chr21,36161901,NaN,GCA,G,NaN,multiallelic,AS_FilterStatus=contamination|SITE;AS_SB_TABLE...,GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:169,5,8:0.043,0.046:182:78,2,5:84,3,3:92..."
40499,UEB_10,chr21,36162841,36162841,C,T,UTR3,RUNX1,NM_001754:c.*1591G>A;NM_001001890:c.*1591G>A,NaN,...,chr21,36162841,NaN,C,T,NaN,contamination;weak_evidence,"AS_FilterStatus=weak_evidence,contamination;AS...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:246,4:0.017:250:117,2:123,2:120,126,2,2"
40500,UEB_10,chr21,36164405,36164405,G,T,UTR3,RUNX1,NM_001754:c.*27C>A;NM_001001890:c.*27C>A,NaN,...,chr21,36164405,NaN,G,T,NaN,panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=98,98|119,105...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:196,224:0.552:420:89,120:103,97:98,98,119,105"
40502,UEB_10,chr21,36193871,36193871,T,C,UTR3,RUNX1,NM_001122607:c.*94A>G,NaN,...,chr21,36193871,NaN,T,C,NaN,panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=0,0|110,110;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:0,220:0.993:220:0,118:0,99:0,0,110,110"
40508,UEB_10,chr21,36259539,36259539,-,G,UTR5,RUNX1,NM_001001890:c.-131_-130insC;NM_001122607:c.-1...,NaN,...,chr21,36259539,NaN,T,TG,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=83,5|58,0;DP=...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:88,58:0.408:146:43,27:24,20:83,5,58,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2134917,UEB_86,chr21,36161882,36161883,CA,-,UTR3,RUNX1,NM_001754:c.*2550_*2549delTG;NM_001001890:c.*2...,NaN,...,chr21,36161881,NaN,TCA,T,NaN,slippage;weak_evidence,"AS_FilterStatus=weak_evidence;AS_SB_TABLE=52,6...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:113,8:0.064:121:54,4:58,4:52,61,5,3"
2134918,UEB_86,chr21,36161902,36161903,CA,-,UTR3,RUNX1,NM_001754:c.*2530_*2529delTG;NM_001001890:c.*2...,NaN,...,chr21,36161901,NaN,GCA,G,NaN,slippage;weak_evidence,"AS_FilterStatus=weak_evidence;AS_SB_TABLE=81,5...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:137,8:0.063:145:67,4:68,3:81,56,5,3"
2134919,UEB_86,chr21,36164405,36164405,G,T,UTR3,RUNX1,NM_001754:c.*27C>A;NM_001001890:c.*27C>A,NaN,...,chr21,36164405,NaN,G,T,NaN,panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=15,11|26,27;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:26,53:0.688:79:13,26:13,27:15,11,26,27"
2134921,UEB_86,chr21,36193871,36193871,T,C,UTR3,RUNX1,NM_001122607:c.*94A>G,NaN,...,chr21,36193871,NaN,T,C,NaN,panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=0,0|79,112;DP...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:0,191:0.992:191:0,110:0,81:0,0,79,112"
2134926,UEB_86,chr21,36259539,36259539,-,G,UTR5,RUNX1,NM_001001890:c.-131_-130insC;NM_001122607:c.-1...,NaN,...,chr21,36259539,NaN,T,TG,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=66,1|37,0;DP=...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:67,37:0.340:104:36,20:23,13:66,1,37,0"

In [77]:
x = df_UTR[df_UTR['Sample']=='UEB_12']
print(x['ClinVar_SIG'].to_list())
x

[nan, 'Uncertain significance', 'Likely benign', 'Benign|Benign', nan, nan]

,Sample,Chr,Start,End,Ref,Alt,Func.refGene,Gene.refGene,GeneDetail.refGene,ExonicFunc.refGene,...,Otherinfo.3,Otherinfo.4,Otherinfo.5,Otherinfo.6,Otherinfo.7,Otherinfo.8,Otherinfo.9,Otherinfo.10,Otherinfo.11,Otherinfo.12
84666,UEB_12,chr21,36161882,36161883,CA,-,UTR3,RUNX1,NM_001754:c.*2550_*2549delTG;NM_001001890:c.*2...,NaN,...,chr21,36161881,NaN,TCA,T,NaN,slippage;weak_evidence,"AS_FilterStatus=weak_evidence;AS_SB_TABLE=92,1...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:205,10:0.044:215:109,8:90,2:92,113,6,4"
84667,UEB_12,chr21,36161901,36161901,-,CA,UTR3,RUNX1,NM_001754:c.*2530_*2531insTG;NM_001001890:c.*2...,NaN,...,chr21,36161901,NaN,G,GCA,NaN,contamination;slippage;weak_evidence,"AS_FilterStatus=weak_evidence,contamination;AS...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:219,6:0.034:225:122,2:91,4:116,103,3,3"
84668,UEB_12,chr21,36162239,36162239,C,-,UTR3,RUNX1,NM_001754:c.*2193delG;NM_001001890:c.*2193delG,NaN,...,chr21,36162238,NaN,AC,A,NaN,panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=32,28|23,24;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:60,47:0.452:107:24,20:35,27:32,28,23,24"
84669,UEB_12,chr21,36164405,36164405,G,T,UTR3,RUNX1,NM_001754:c.*27C>A;NM_001001890:c.*27C>A,NaN,...,chr21,36164405,NaN,G,T,NaN,panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=1,0|258,217;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:1,475:0.997:476:0,238:0,226:1,0,258,217"
84673,UEB_12,chr21,36193871,36193871,T,C,UTR3,RUNX1,NM_001122607:c.*94A>G,NaN,...,chr21,36193871,NaN,T,C,NaN,panel_of_normals,"AS_FilterStatus=SITE;AS_SB_TABLE=0,0|102,191;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:0,293:0.996:293:0,153:0,139:0,0,102,191"
84679,UEB_12,chr21,36259540,36259540,G,-,UTR5,RUNX1,NM_001001890:c.-131delC;NM_001122607:c.-131delC,NaN,...,chr21,36259539,NaN,TG,T,NaN,contamination;slippage;weak_evidence,"AS_FilterStatus=weak_evidence,contamination;AS...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:176,7:0.033:183:85,4:50,1:173,3,7,0"

In [83]:
z = list(x['GeneDetail.refGene'])
z

['NM_001754:c.*2550_*2549delTG;NM_001001890:c.*2550_*2549delTG',
 'NM_001754:c.*2530_*2531insTG;NM_001001890:c.*2530_*2531insTG',
 'NM_001754:c.*2193delG;NM_001001890:c.*2193delG',
 'NM_001754:c.*27C>A;NM_001001890:c.*27C>A',
 'NM_001122607:c.*94A>G',
 'NM_001001890:c.-131delC;NM_001122607:c.-131delC']

In [ ]:
# Not found, Not found, Benigna, Benigna, Benigna, VUS

# UTR

In [84]:
df = pd.read_csv('/home/fer/Documents/cfDNA/Tumor/FiltradoFinal.txt', sep = '\t')
df

,Sample,Chr,Start,End,Ref,Alt,Func.refGene,Gene.refGene,GeneDetail.refGene,ExonicFunc.refGene,...,Otherinfo.7,Otherinfo.8,Otherinfo.9,Otherinfo.10,Otherinfo.11,Otherinfo.12,GT,ADref,ADalt,AF
0,UEB_10,chr3,178921553,178921553,T,A,exonic,PIK3CA,NaN,nonsynonymous SNV,...,A,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=130,137|8,8;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:267,16:0.056:283:139,4:127,12:130,137,8,8",0/1,267,16,0.056
1,UEB_29,chr3,178952085,178952085,A,G,exonic,PIK3CA,NaN,nonsynonymous SNV,...,G,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=173,150|42,37...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:323,79:0.186:402:150,30:170,48:173,150,42,37",0/1,323,79,0.186
2,UEB_30,chr3,178952090,178952090,G,C,exonic,PIK3CA,NaN,nonsynonymous SNV,...,C,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=96,66|11,23;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:162,34:0.210:196:74,14:88,18:96,66,11,23",0/1,162,34,0.210
3,UEB_35,chrX,133549085,133549085,A,G,exonic,PHF6,NaN,nonsynonymous SNV,...,G,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=1,1|1,1;DP=4;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:2,2:0.500:4:0,2:2,0:1,1,1,1",0/1,2,2,0.500
4,UEB_39,chr13,32914515,32914515,-,G,exonic,BRCA2,NaN,frameshift insertion,...,AG,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=18,19|22,22;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:37,44:0.540:81:21,27:16,17:18,19,22,22",0/1,37,44,0.540
5,UEB_43,chr3,178952085,178952085,A,G,exonic,PIK3CA,NaN,nonsynonymous SNV,...,G,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=200,173|25,16...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:373,41:0.102:414:176,15:196,26:200,173,25,16",0/1,373,41,0.102
6,UEB_43,chrX,66765158,66765158,-,GCA,exonic,AR,NaN,nonframeshift insertion,...,TGCA,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=9,20|38,70;DP...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:29,108:0.800:137:14,54:15,45:9,20,38,70",0/1,29,108,0.800
7,UEB_47,chr3,178952085,178952085,A,G,exonic,PIK3CA,NaN,nonsynonymous SNV,...,G,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=175,103|64,33...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:278,97:0.270:375:136,49:141,48:175,103,64,33",0/1,278,97,0.270
8,UEB_47,chr22,38379543,38379543,G,A,exonic,SOX10,NaN,synonymous SNV,...,A,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=86,127|41,66;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:213,107:0.330:320:119,57:90,50:86,127,41,66",0/1,213,107,0.330
9,UEB_51,chr3,178952072,178952072,A,G,exonic,PIK3CA,NaN,nonsynonymous SNV,...,G,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=165,171|14,11...",GT:AD:AF:DP:F1R2:F2R1:PGT:PID:PS:SB,"0|1:336,25:0.068:361:162,12:174,13:0|1:1789520...",0|1,336,25,0.068
10,UEB_53,chr3,178952085,178952085,A,G,exonic,PIK3CA,NaN,nonsynonymous SNV,...,G,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=147,115|49,38...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:262,87:0.257:349:149,52:112,35:147,115,49,38",0/1,262,87,0.257
11,UEB_53,chr9,21971186,21971186,G,A,exonic,CDKN2A,NaN,stopgain,...,A,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=252,279|73,86...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:531,159:0.239:690:274,81:254,76:252,279,73,86",0/1,531,159,0.239
12,UEB_53,chr17,7578478,7578478,G,C,exonic,TP53,NaN,nonsynonymous SNV,...,C,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=150,392|56,11...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:542,170:0.229:712:281,84:258,80:150,392,56...",0/1,542,170,0.229
13,UEB_78,chr3,178936091,178936091,G,A,exonic,PIK3CA,NaN,nonsynonymous SNV,...,A,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=26,22|7,5;DP=...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:48,12:0.212:60:27,5:21,7:26,22,7,5",0/1,48,12,0.212
14,UEB_78,chr10,123258034,123258034,A,T,exonic,FGFR2,NaN,nonsynonymous SNV,...,T,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=24,51|3,6;DP=...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:75,9:0.107:84:43,2:31,7:24,51,3,6",0/1,75,9,0.107
15,UEB_83,chr13,48954175,48954175,A,T,intronic,RB1,NaN,NaN,...,T,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=5,3|9,3;DP=21...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:8,12:0.629:20:3,8:5,4:5,3,9,3",0/1,8,12,0.629
16,UEB_8,chr17,7578203,7578203,C,T,exonic,TP53,NaN,nonsynonymous SNV,...,T,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=165,80|12,5;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:245,17:0.072:262:107,4:137,12:165,80,12,5",0/1,245,17,0.072
17,UEB_8,chr17,41244214,41244217,CTTG,-,exonic,BRCA1,NaN,frameshift deletion,...,T,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=56,32|55,38;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:88,93:0.519:181:38,46:49,47:56,32,55,38",0/1,88,93,0.519
18,UEB_27,chr13,28589763,28589763,A,G,exonic,FLT3,NaN,nonsynonymous SNV,...,G,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=57,19|39,25;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:76,64:0.418:140:44,37:31,24:57,19,39,25",0/1,76,64,0.418
19,UEB_5,chr6,34857343,34857343,G,A,exonic,ANKS1A,NaN,nonsynonymous SNV,...,A,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=2,3|1,1;DP=7;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:5,2:0.333:7:2,2:3,0:2,3,1,1",0/1,5,2,0.333
20,UEB_81,chr17,29586129,29586129,A,G,exonic,NF1,NaN,nonsynonymous SNV,...,G,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=27,45|18,33;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:72,51:0.414:123:31,16:41,35:27,45,18,33",0/1,72,51,0.414
21,UEB_10,chr7,55211109,55211109,G,T,exonic,EGFR,NaN,nonsynonymous SNV,...,T,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=106,88|87,93;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:194,180:0.495:374:95,99:97,80:106,88,87,93",0/1,194,180,0.495
22,UEB_14,chr14,104038131,104038131,G,A,exonic,APOPT1,NaN,nonsynonymous SNV,...,A,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=1,1|1,1;DP=4;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:2,2:0.500:4:2,2:0,0:1,1,1,1",0/1,2,2,0.500
23,UEB_25,chr1,161140703,161140703,A,G,exonic,PPOX,NaN,nonsynonymous SNV,...,G,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=1,1|1,1;DP=4;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:2,2:0.414:4:1,0:0,2:1,1,1,1",0/1,2,2,0.414
24,UEB_25,chr7,100867039,100867039,G,T,exonic,ZNHIT1,NaN,nonsynonymous SNV,...,T,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=1,1|1,1;DP=4;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:2,2:0.500:4:2,2:0,0:1,1,1,1",0/1,2,2,0.500
25,UEB_25,chr10,21805976,21805976,G,A,exonic,SKIDA1,NaN,nonsynonymous SNV,...,A,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=4,2|1,1;DP=8;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:6,2:0.286:8:1,2:5,0:4,2,1,1",0/1,6,2,0.286
26,UEB_27,chr3,114058240,114058240,C,T,exonic,ZBTB20,NaN,nonsynonymous SNV,...,T,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=1,1|1,1;DP=4;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:2,2:0.500:4:0,2:2,0:1,1,1,1",0/1,2,2,0.500
27,UEB_27,chrX,18972524,18972524,C,A,exonic,PHKA2,NaN,nonsynonymous SNV,...,A,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=1,1|1,1;DP=4;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:2,2:0.500:4:0,2:2,0:1,1,1,1",0/1,2,2,0.500
28,UEB_30,chr20,61512305,61512305,A,G,exonic,DIDO1,NaN,nonsynonymous SNV,...,G,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=1,1|1,1;DP=4;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:2,2:0.500:4:2,0:0,2:1,1,1,1",0/1,2,2,0.500
29,UEB_35,chr16,67876756,67876756,C,T,exonic,THAP11,NaN,nonsynonymous SNV,...,T,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=2,1|1,1;DP=5;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:3,2:0.400:5:3,2:0,0:2,1,1,1",0/1,3,2,0.400
30,UEB_37,chr1,154842058,154842058,C,T,exonic,KCNN3,NaN,nonsynonymous SNV,...,T,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=7,0|2,0;DP=12...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:7,2:0.268:9:5,2:2,0:7,0,2,0",0/1,7,2,0.268
31,UEB_37,chr21,36164678,36164678,G,C,exonic,RUNX1,NaN,nonsynonymous SNV,...,C,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=96,89|83,91;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:185,174:0.485:359:107,77:76,94:96,89,83,91",0/1,185,174,0.485
32,UEB_43,chr17,37686896,37686896,C,T,exonic,CDK12,NaN,nonsynonymous SNV,...,T,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=44,77|77,84;D...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:121,161:0.574:282:67,81:54,78:44,77,77,84",0/1,121,161,0.574
33,UEB_80,chr6,26273235,26273235,C,T,exonic,HIST1H2BI,NaN,nonsynonymous SNV,...,T,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=3,1|1,1;DP=6;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:4,2:0.286:6:1,0:3,2:3,1,1,1",0/1,4,2,0.286
34,UEB_80,chrX,70627445,70627445,C,T,exonic,TAF1,NaN,nonsynonymous SNV,...,T,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=34,48|2,2;DP=...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:82,4:0.050:86:38,2:44,2:34,48,2,2",0/1,82,4,0.050
35,UEB_81,chr16,1033763,1033763,A,G,exonic,SOX8,NaN,nonsynonymous SNV,...,G,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=1,2|1,1;DP=5;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:3,2:0.400:5:0,0:3,2:1,2,1,1",0/1,3,2,0.400
36,UEB_83,chr5,45696030,45696030,A,G,exonic,HCN1,NaN,nonsynonymous SNV,...,G,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=0,2|1,1;DP=4;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:2,2:0.400:4:1,2:1,0:0,2,1,1",0/1,2,2,0.400
37,UEB_8,chrX,70360622,70360622,A,T,exonic,MED12,NaN,nonsynonymous SNV,...,T,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=2,1|1,1;DP=5;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:3,2:0.400:5:2,2:1,0:2,1,1,1",0/1,3,2,0.400
38,UEB_30,chr16,30663117,30663117,C,A,exonic,PRR14,NaN,nonsynonymous SNV,...,A,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=1,1|1,1;DP=4;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:2,2:0.500:4:2,2:0,0:1,1,1,1",0/1,2,2,0.500
39,UEB_84,chr19,53075522,53075522,G,T,exonic,ZNF701,NaN,nonsynonymous SNV,...,T,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=1,1|1,1;DP=4;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:2,2:0.500:4:2,0:0,2:1,1,1,1",0/1,2,2,0.500
40,UEB_29,chr22,20918846,20918846,G,T,exonic,MED15,NaN,nonsynonymous SNV,...,T,NaN,PASS,"AS_FilterStatus=SITE;AS_SB_TABLE=1,1|1,1;DP=4;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:2,2:0.500:4:2,0:0,2:1,1,1,1",0/1,2,2,0.500